import type { CropRecommendation } from "@/types";

export const MOCK_ROTATIONS: Record<string, CropRecommendation[]> = {
  "field-ke-002": [
    {
      id: "rot-sorghum",
      cropName: "Sorghum",
      suitabilityScore: 88,
      waterDemand: "low",
      plantingWindow: { start: "10-05", end: "11-15" },
      climateResilienceTags: ["Drought-tolerant", "Heat-tolerant", "Low input"],
      rationale: "Sorghum's deep root system handles the current soil-moisture deficit far better than maize, and matches the region's shortened rain window.",
    },
    {
      id: "rot-cowpea",
      cropName: "Cowpea",
      suitabilityScore: 74,
      waterDemand: "low",
      plantingWindow: { start: "10-10", end: "11-20" },
      climateResilienceTags: ["Drought-tolerant", "Nitrogen-fixing"],
      rationale: "Fixes nitrogen ahead of the next maize cycle and tolerates the projected dry spell, at a modest yield trade-off.",
    },
    {
      id: "rot-maize-again",
      cropName: "Maize (repeat)",
      suitabilityScore: 31,
      waterDemand: "high",
      plantingWindow: { start: "10-01", end: "10-20" },
      climateResilienceTags: ["High water demand"],
      rationale: "Repeating maize under the current SMAP/ECOSTRESS trend carries a high failure risk this cycle — not recommended.",
    },
  ],
  "field-pb-011": [
    {
      id: "rot-mungbean",
      cropName: "Mung Bean",
      suitabilityScore: 81,
      waterDemand: "low",
      plantingWindow: { start: "03-15", end: "04-10" },
      climateResilienceTags: ["Drought-tolerant", "Nitrogen-fixing", "Short cycle"],
      rationale: "A short-cycle legume break between wheat seasons rebuilds soil nitrogen and needs a fraction of wheat's irrigation demand.",
    },
    {
      id: "rot-wheat-again",
      cropName: "Wheat (repeat)",
      suitabilityScore: 62,
      waterDemand: "medium",
      plantingWindow: { start: "11-01", end: "11-25" },
      climateResilienceTags: ["Established rotation"],
      rationale: "Viable if irrigation timing shifts 5–7 days later per this cycle's Shift Score recommendation.",
    },
    {
      id: "rot-pearlmillet",
      cropName: "Pearl Millet",
      suitabilityScore: 79,
      waterDemand: "low",
      plantingWindow: { start: "06-20", end: "07-10" },
      climateResilienceTags: ["Drought-tolerant", "Heat-tolerant"],
      rationale: "Strong fallback for the next kharif cycle if the aquifer anomaly deepens further.",
    },
  ],
  "field-ia-004": [
    {
      id: "rot-cover-clover",
      cropName: "Crimson Clover (cover)",
      suitabilityScore: 85,
      waterDemand: "medium",
      plantingWindow: { start: "09-15", end: "10-05" },
      climateResilienceTags: ["Nitrogen-fixing", "Soil-building"],
      rationale: "Field is healthy — a winter cover crop protects the strong soil-moisture position through the off-season.",
    },
    {
      id: "rot-soybean",
      cropName: "Soybean",
      suitabilityScore: 90,
      waterDemand: "medium",
      plantingWindow: { start: "05-01", end: "05-25" },
      climateResilienceTags: ["Nitrogen-fixing", "Established rotation"],
      rationale: "Standard corn–soy rotation remains optimal given current signal trends.",
    },
  ],
  "field-br-007": [
    {
      id: "rot-soy-repeat",
      cropName: "Soybean (repeat)",
      suitabilityScore: 66,
      waterDemand: "medium",
      plantingWindow: { start: "09-20", end: "10-15" },
      climateResilienceTags: ["Established rotation"],
      rationale: "Fine short-term, but rising evapotranspiration means water stress should be watched closely mid-cycle.",
    },
    {
      id: "rot-brachiaria",
      cropName: "Brachiaria (cover)",
      suitabilityScore: 83,
      waterDemand: "low",
      plantingWindow: { start: "09-25", end: "10-20" },
      climateResilienceTags: ["Drought-tolerant", "Soil-building"],
      rationale: "A grass cover break would rebuild soil structure and ease the evapotranspiration pressure before the next soy cycle.",
    },
  ],
};
