import type { ShiftScore } from "@/types";
import { riskBandForScore } from "@/types";

export const MOCK_SHIFT_SCORES: Record<string, ShiftScore> = {
  "field-ia-004": {
    fieldId: "field-ia-004",
    score: 82,
    riskBand: riskBandForScore(82),
    recommendation: "continue",
    confidence: 0.91,
    computedAt: "2026-09-26T06:00:00Z",
    summary: "Soil moisture and canopy vigor are both tracking above the 10-year seasonal norm. Current rotation holds.",
    signalBreakdown: [
      {
        signal: "SMAP",
        label: "Soil Moisture",
        contribution: 18,
        weight: 0.3,
        rawValue: 0.31,
        unit: "m³/m³",
        observedAt: "2026-09-25",
        trend: "stable",
      },
      {
        signal: "MODIS",
        label: "Vegetation Index (NDVI)",
        contribution: 14,
        weight: 0.25,
        rawValue: 0.79,
        unit: "NDVI",
        observedAt: "2026-09-24",
        trend: "rising",
      },
      {
        signal: "ECOSTRESS",
        label: "Evapotranspiration",
        contribution: 6,
        weight: 0.15,
        rawValue: 4.1,
        unit: "mm/day",
        observedAt: "2026-09-23",
        trend: "stable",
      },
      {
        signal: "GPM_IMERG",
        label: "Rainfall Outlook",
        contribution: 8,
        weight: 0.15,
        rawValue: 22.4,
        unit: "mm / 7d",
        observedAt: "2026-09-26",
        trend: "rising",
      },
      {
        signal: "GRACE_FO",
        label: "Aquifer Anomaly",
        contribution: -2,
        weight: 0.15,
        rawValue: -0.6,
        unit: "cm equiv.",
        observedAt: "2026-09-20",
        trend: "falling",
      },
    ],
  },
  "field-pb-011": {
    fieldId: "field-pb-011",
    score: 58,
    riskBand: riskBandForScore(58),
    recommendation: "adjust_timing",
    confidence: 0.84,
    computedAt: "2026-09-26T06:00:00Z",
    summary: "Groundwater drawdown and a drying topsoil signal suggest delaying the next irrigation-dependent stage by 5–7 days.",
    signalBreakdown: [
      {
        signal: "SMAP",
        label: "Soil Moisture",
        contribution: -22,
        weight: 0.3,
        rawValue: 0.14,
        unit: "m³/m³",
        observedAt: "2026-09-25",
        trend: "falling",
      },
      {
        signal: "MODIS",
        label: "Vegetation Index (NDVI)",
        contribution: 9,
        weight: 0.25,
        rawValue: 0.61,
        unit: "NDVI",
        observedAt: "2026-09-24",
        trend: "stable",
      },
      {
        signal: "ECOSTRESS",
        label: "Evapotranspiration",
        contribution: -8,
        weight: 0.15,
        rawValue: 6.8,
        unit: "mm/day",
        observedAt: "2026-09-23",
        trend: "rising",
      },
      {
        signal: "GPM_IMERG",
        label: "Rainfall Outlook",
        contribution: 14,
        weight: 0.15,
        rawValue: 31.2,
        unit: "mm / 7d",
        observedAt: "2026-09-26",
        trend: "rising",
      },
      {
        signal: "GRACE_FO",
        label: "Aquifer Anomaly",
        contribution: -17,
        weight: 0.15,
        rawValue: -3.4,
        unit: "cm equiv.",
        observedAt: "2026-09-19",
        trend: "falling",
      },
    ],
  },
  "field-ke-002": {
    fieldId: "field-ke-002",
    score: 39,
    riskBand: riskBandForScore(39),
    recommendation: "shift_crop",
    confidence: 0.77,
    computedAt: "2026-09-26T06:00:00Z",
    summary: "Sustained low soil moisture with declining vegetation vigor crosses the threshold for a drought-tolerant crop swap this cycle.",
    signalBreakdown: [
      {
        signal: "SMAP",
        label: "Soil Moisture",
        contribution: -26,
        weight: 0.3,
        rawValue: 0.09,
        unit: "m³/m³",
        observedAt: "2026-09-25",
        trend: "falling",
      },
      {
        signal: "MODIS",
        label: "Vegetation Index (NDVI)",
        contribution: -11,
        weight: 0.25,
        rawValue: 0.38,
        unit: "NDVI",
        observedAt: "2026-09-24",
        trend: "falling",
      },
      {
        signal: "ECOSTRESS",
        label: "Evapotranspiration",
        contribution: -9,
        weight: 0.15,
        rawValue: 7.9,
        unit: "mm/day",
        observedAt: "2026-09-23",
        trend: "rising",
      },
      {
        signal: "GPM_IMERG",
        label: "Rainfall Outlook",
        contribution: -4,
        weight: 0.15,
        rawValue: 6.1,
        unit: "mm / 7d",
        observedAt: "2026-09-26",
        trend: "falling",
      },
      {
        signal: "GRACE_FO",
        label: "Aquifer Anomaly",
        contribution: -5,
        weight: 0.15,
        rawValue: -1.8,
        unit: "cm equiv.",
        observedAt: "2026-09-18",
        trend: "falling",
      },
    ],
  },
  "field-br-007": {
    fieldId: "field-br-007",
    score: 67,
    riskBand: riskBandForScore(67),
    recommendation: "adjust_timing",
    confidence: 0.88,
    computedAt: "2026-09-26T06:00:00Z",
    summary: "Moisture and canopy health remain solid, but a widening evapotranspiration gap warrants closer monitoring before the next planting window.",
    signalBreakdown: [
      {
        signal: "SMAP",
        label: "Soil Moisture",
        contribution: 11,
        weight: 0.3,
        rawValue: 0.24,
        unit: "m³/m³",
        observedAt: "2026-09-25",
        trend: "stable",
      },
      {
        signal: "MODIS",
        label: "Vegetation Index (NDVI)",
        contribution: 13,
        weight: 0.25,
        rawValue: 0.74,
        unit: "NDVI",
        observedAt: "2026-09-24",
        trend: "stable",
      },
      {
        signal: "ECOSTRESS",
        label: "Evapotranspiration",
        contribution: -12,
        weight: 0.15,
        rawValue: 7.2,
        unit: "mm/day",
        observedAt: "2026-09-23",
        trend: "rising",
      },
      {
        signal: "GPM_IMERG",
        label: "Rainfall Outlook",
        contribution: 4,
        weight: 0.15,
        rawValue: 18.6,
        unit: "mm / 7d",
        observedAt: "2026-09-26",
        trend: "stable",
      },
      {
        signal: "GRACE_FO",
        label: "Aquifer Anomaly",
        contribution: 1,
        weight: 0.15,
        rawValue: 0.2,
        unit: "cm equiv.",
        observedAt: "2026-09-17",
        trend: "stable",
      },
    ],
  },
};
